apiVersion: v1  #initialize database throught mongo-init-script
kind: ConfigMap
metadata:
  name: mongo-init-script
data:
  init.js: |
    db.createUser({
      user: "adminuser",
      pwd: "password",
      roles: [{ role: "readWrite", db: "mydb" }]
    });
